### ISSUE TITLE
repeated primitive as Array of primitives

### ISSUE THREAD

**Issue by lxomb** [zero-deps/protobuf-scala-macros#26]
Looks like using arrays as collections are not supported at all. But using primitive arrays is crucial when storing & loading very large amount of primitives.

**Comment by tellnobody1** [comment]
Why not to use `scala.collection.immutable.ArraySeq`? Building an Array is just a big overhead of constant copying.

**Comment by lxomb** [comment]
> Why not to use `scala.collection.immutable.ArraySeq`? Building an Array is just a big overhead of constant copying.

There's no way to define a fully specialized Seq in scala 2.12 & 2.13. Even if immutable.ArraySeq has elements unboxed, accessing elements with boxing overhead is unacceptable in my use case. Array is always the simplest alternative when no encapsulated ones fit the need. When you can simply fallback to Array, having to rely on complicated dirty tricks hurts maintainability and readability a lot. And again, when Collections are supported, one can naturally expect that Arrays are supported as well, supporting Collections but not Arrays is quite surprising.

**Comment by lxomb** [comment]
> Why not to use `scala.collection.immutable.ArraySeq`? Building an Array is just a big overhead of constant copying.

And about constant copying, as long as number of elements is not known beforehand (which is the case of protobuf), some copying is always needed for both ArraySeq and Array. And with `scala.collection.mutable.ArrayBuilder`, arrays can be built as efficient as `scala.collection.immutable.ArraySeq`, with only one extra copy at the end to erase the extra space, which should be very fast.
