### ISSUE TITLE
scala 2.12 support

### ISSUE THREAD

**Issue by lxomb** [zero-deps/protobuf-scala-macros#28]
Currently Spark 3.0 supports only scala 2.12. It will be very convenient if proto supports scala 2.12 as well. I've created a fork for 2.12 only, and only a few changes are needed. However I don't know how to get it to work on 2.12 and 2.13 at the same time.

**Comment by tellnobody1** [comment]
It should work with to directories: `scala_2.13` and `scala_2.12`.

**Comment by tellnobody1** [comment]
https://repo1.maven.org/maven2/io/github/zero-deps/proto_2.12/2.1.1/proto_2.12-2.1.1.pom
