### ISSUE TITLE
handle unknown fields for sealed traits

### ISSUE THREAD

**Issue by shmishleniy** [zero-deps/protobuf-scala-macros#5]
handle unknown fields for
- Option[SealedTrait]
- List[SealedTrait]

**Comment by tellnobody1** [comment]
@shmishleniy It is not clear what is use case for this functionality.
This functionality can't be enabled by default because you can loose data on decode/encode.
Also, example of client code for that feature will be useful.

**Comment by tellnobody1** [comment]
Closed because of inactivity.
